/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Tue Jan 10 21:21:34 2023 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
