/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.8 */
/* Sat Jan 14 22:42:31 2023 */

/* parameterized module instance */
sdr __ (.clkin( ), .reset( ), .sclk( ), .datain( ), .q( ));
